StylesPath = .vale/styles
MinAlertLevel = suggestion
Packages = Google

[src/content/articles/*.md]
BasedOnStyles = Google
# A personal blog is written in first person.
Google.FirstPerson = NO
Google.We = NO
