StylesPath = .vale/styles
MinAlertLevel = suggestion
Packages = Google, proselint

[{src/content/articles/*.md,**/src/content/articles/*.md}]
BasedOnStyles = Google, proselint
# A personal blog is written in first person.
Google.FirstPerson = NO
Google.We = NO
