import fs from 'node:fs';
import en from './en.json';

export type Strings = typeof en;
export type StringKey = keyof Strings;

export const LANGS = ['en', 'ja', 'zh-tw'] as const;
export type Lang = (typeof LANGS)[number];

export const LANG_META: Record<Lang, { label: string; htmlLang: string; dateLocale: string; giscus: string; ogLocale: string }> = {
  en: { label: 'EN', htmlLang: 'en', dateLocale: 'en-US', giscus: 'en', ogLocale: 'en_US' },
  ja: { label: '日本語', htmlLang: 'ja', dateLocale: 'ja-JP', giscus: 'ja', ogLocale: 'ja_JP' },
  'zh-tw': { label: '中文', htmlLang: 'zh-Hant-TW', dateLocale: 'zh-TW', giscus: 'zh-TW', ogLocale: 'zh_TW' },
};

// Machine translations live in translations/<lang>/ (generated by Claude Code, see AGENTS.md).
// Each UI string records the English text it was translated from; if the English has since
// changed, that string falls back to English. A language is offered only when its ui.json exists.
const TRANSLATIONS_DIR = 'translations';

type UiFile = Record<string, { source: string; text: string }>;

function readUi(lang: Lang): Partial<Strings> | null {
  let file: UiFile;
  try {
    file = JSON.parse(fs.readFileSync(`${TRANSLATIONS_DIR}/${lang}/ui.json`, 'utf8'));
  } catch {
    return null;
  }
  const strings: Partial<Strings> = {};
  for (const key of Object.keys(en) as StringKey[]) {
    const entry = file[key];
    if (entry && entry.source === en[key]) strings[key] = entry.text;
  }
  return strings;
}

export function availableLangs(): Lang[] {
  return LANGS.filter((lang) => lang === 'en' || readUi(lang) !== null);
}

export function translatedLangs(): Lang[] {
  return availableLangs().filter((lang) => lang !== 'en');
}

export function useStrings(lang: Lang) {
  const strings: Strings = lang === 'en' ? en : { ...en, ...readUi(lang) };
  return (key: StringKey, vars: Record<string, string | number> = {}) =>
    strings[key].replace(/\{(\w+)\}/g, (_, name) => String(vars[name] ?? `{${name}}`));
}

/** "/articles/" in Japanese is "/ja/articles/"; English has no prefix. */
export function localizePath(path: string, lang: Lang) {
  return lang === 'en' ? path : `/${lang}${path}`;
}

/** Splits "/ja/articles/x/" into { lang: "ja", path: "/articles/x/" }. */
export function splitLangPath(pathname: string): { lang: Lang; path: string } {
  const match = pathname.match(/^\/(ja|zh-tw)(\/.*|$)/);
  if (match) return { lang: match[1] as Lang, path: match[2] || '/' };
  return { lang: 'en', path: pathname };
}

export function formatDateFor(lang: Lang, date: Date) {
  return date.toLocaleDateString(LANG_META[lang].dateLocale, { year: 'numeric', month: 'short', day: 'numeric' });
}
